name: Install GCC

on: [push, pull_request]

jobs:
  install-gcc:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc g++13 
      
    - name: Verify GCC installation
      run: |
        gcc --version
        g++ --version
