name: Install Requirements

on: [push,pull_request]

jobs:
  install-requirements:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install requirements.txt
      run: |
        ls -l
        node --version
        python --version
        pip --version
        python3 -m pip install -r "./requirements.txt"
