name: Install WSL2

on: [push,pull_request]

jobs:
  install-wsl2:
    runs-on: windows-2025

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get latest WSL release version
      shell: pwsh
      run: |
        $version = (Get-GithubReleasesByVersion -Repo "microsoft/WSL" -Version "latest").version
        echo "Latest WSL version: $version"

    - name: Install WSL2
      shell: pwsh
      run: |
        wsl --install --no-distribution

    - name: Check WSL status
      shell: pwsh
      run: |
        wsl --status

    - name: Check WSL version
      shell: pwsh
      run: |
        wsl --version

    - name: Update WSL
      shell: pwsh
      run: |
        wsl --update
