name: Install WSL2 and Verify Installation

on: [push,pull_request]

jobs:
  install_wsl:
    runs-on: windows-2025

    steps:
      # Checkout the code (if necessary for your script)
      - name: Checkout Repository
        uses: actions/checkout@v4

  

      # Install WSL2 manually via MSI
      - name: Install WSL2
        shell: pwsh
        run: |
          Write-Host "Install WSL2"
          
          # Fetch the latest version from GitHub
          $version = (Invoke-RestMethod -Uri "https://api.github.com/repos/microsoft/WSL/releases/latest").tag_name
          Write-Host "Latest WSL version: $version"
          
          # Build the download URL
          $downloadUrl = "https://github.com/microsoft/WSL/releases/download/$version/wsl-$version.msi"
          Write-Host "Download URL: $downloadUrl"
          
          # Download the WSL MSI installer
          $installerPath = "$env:TEMP\wsl-installer.msi"
          Invoke-WebRequest -Uri $downloadUrl -OutFile $installerPath
          
          # Install WSL MSI
          Start-Process msiexec.exe -ArgumentList "/i", $installerPath, "/quiet", "/norestart" -Wait
          Write-Host "WSL installation completed."

      # Install WSL without a distribution
      - name: Perform wsl --install --no-distribution
        shell: pwsh
        run: |
          Write-Host "Performing wsl --install --no-distribution"
          wsl.exe --install --no-distribution

      # Verify WSL installation status and version
      - name: Check WSL Status and Version
        shell: pwsh
        run: |
          Write-Host "Checking WSL Status"
          wsl --status
          
          Write-Host "Checking WSL Version"
          wsl --version
          
          Write-Host "Updating WSL"
          wsl --update

      # Run Pester tests (or your custom testing framework)
      - name: Run Pester Tests
        shell: pwsh
        run: |
          Write-Host "Running Pester Tests"
          Invoke-Pester -TestFile "WindowsFeatures.Tests.ps1" -TestName "WSL2"
